Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-09, with the labels that each got.

#261 feat: improve container API
  src/schemas/ContainerEditRequest.yaml
  src/schemas/ContainerRegistryRequest.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/enums/ContainerRegistryKind.yaml
Labels: enhancement

#262 feat: add get container api call
  generator/post_generation_scripts/go.sh
  src/resources/OrganizationContainerRegistryRef.yaml
Labels: enhancement

#263 fix: Forbid create / edit an environment with PREVIEW mode
  src/resources/ProjectEnvironment.yaml
  src/schemas/CreateEnvironmentRequest.yaml
  src/schemas/EnvironmentEditRequest.yaml
  src/schemas/_index.yaml
  src/schemas/enums/CreateEnvironmentMode.yaml
Labels: bug

#264 chore: upgrade generator version
  .github/workflows/generate-clients.yaml
Labels: chore

#266 fix: set container registry config properties
  src/schemas/ContainerRegistryRequest.yaml
Labels: enhancement

#268 fix: replace ContainerEditRequest by ContainerRequest
  src/resources/Container.yaml
  src/schemas/ContainerEditRequest.yaml
  src/schemas/_index.yaml
Labels: enhancement

#271 fix: cluster features type
  src/schemas/ClusterRequest.yaml
Labels: enhancement

#270 fix: tags name for container secret override
  src/resources/ContainerSecretOverride.yaml
Labels: enhancement

#269 fix: add container deployment history type
  src/schemas/_index.yaml
Labels: enhancement

#272 fix: container type for env deployment
  src/schemas/DeploymentHistoryEnvironmentResponse.yaml
Labels: enhancement

#273 fix: List available container registries
  src/resources/AvailableContainerRegistry.yaml
  src/schemas/AvailableContainerRegistryResponse.yaml
  src/schemas/AvailableContainerRegistryResponseList.yaml
Labels: bug

#274 fix: Declare missing types
  src/schemas/_index.yaml
Labels: bug

#275 removed not existing link endpoint for environments
  src/openapi.yaml
  src/resources/EnvironmentLink.yaml
Labels: bug

#276 fix: Remove mandatory port id when creating application
  src/schemas/ApplicationRequest.yaml
  src/schemas/ServicePortRequestList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/PortProtocol.yaml
Labels: enhancement

#278 fix: Remove inner array for application ports
  src/schemas/ApplicationRequest.yaml
  src/schemas/_index.yaml
Labels: bug

#280 Fix wording deploy app
  src/resources/EnvironmentApplicationDeploy.yaml
Labels: bug

#279 feat: Improve organization role API
  src/openapi.yaml
  src/parameters/path/customRoleId.yaml
  src/resources/OrganizationAvailableRole.yaml
  src/resources/OrganizationCustomRole.yaml
  src/resources/OrganizationCustomRoleRef.yaml
  src/resources/OrganizationMember.yaml
  src/schemas/MemberResponse.yaml
  src/schemas/MemberRoleUpdateRequest.yaml
  src/schemas/OrganizationAvailableRoleResponse.yaml
  src/schemas/OrganizationAvailableRoleResponseList.yaml
  src/schemas/OrganizationCustomRoleCreateOrUpdateRequest.yaml
  src/schemas/OrganizationCustomRoleResponse.yaml
  src/schemas/OrganizationCustomRoleResponseList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/DefaultMemberRole.yaml
  src/schemas/enums/InviteMemberRole.yaml
  src/schemas/enums/OrganizationCustomRoleClusterPermission.yaml
  src/schemas/enums/OrganizationCustomRoleProjectPermission.yaml
Labels: enhancement

#281 feat: Create custom role with lowest permissions
  src/resources/OrganizationCustomRole.yaml
  src/resources/OrganizationCustomRoleRef.yaml
  src/schemas/OrganizationCustomRoleCreateRequest.yaml
  src/schemas/OrganizationCustomRoleUpdateRequest.yaml
  src/schemas/_index.yaml
Labels: enhancement

#283 feat: add websocket and grpc ingress annotations for containers #COR-499
  src/schemas/ContainerAdvancedSettings.yaml
Labels: new-feature

#285 feat: Gather custom roles with default provided roles
  src/schemas/MemberRoleUpdateRequest.yaml
  src/schemas/OrganizationAvailableRoleResponse.yaml
Labels: enhancement

#286 fix: Edit config for PUBLIC_ECR
  src/schemas/ContainerRegistryRequest.yaml
Labels: enhancement

#287 fix: Make docker hub config optional
  src/schemas/AvailableContainerRegistryResponse.yaml
Labels: enhancement
