Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-03, with the labels that each got.

#163 Typescript axios generation
  .github/workflows/generate-clients.yaml
  generator/configs/go.yaml
  generator/configs/javascript.yaml
  generator/configs/python.yaml
  generator/configs/typescript-axios.yaml
  generator/post_generation_scripts/typescript-axios.sh
  src/schemas/ApplicationEditRequest.yaml
  src/schemas/ApplicationRequest.yaml
  src/schemas/ApplicationResponse.yaml
  src/schemas/BackupResponse.yaml
  src/schemas/BaseResponse.yaml
  src/schemas/ClusterFeatureResponse.yaml
  src/schemas/ClusterRequest.yaml
  src/schemas/ClusterResponse.yaml
  src/schemas/CommitPaginatedResponseList.yaml
  src/schemas/Cost.yaml
  src/schemas/CustomDomainResponse.yaml
  src/schemas/DatabaseResponse.yaml
  src/schemas/DeploymentHistoryApplicationResponse.yaml
  src/schemas/DeploymentHistoryDatabaseResponse.yaml
  src/schemas/DeploymentHistoryEnvironmentPaginatedResponseList.yaml
  src/schemas/DeploymentHistoryEnvironmentResponse.yaml
  src/schemas/DeploymentHistoryPaginatedResponseList.yaml
  src/schemas/DeploymentHistoryResponse.yaml
  src/schemas/EnvironmentDeploymentRuleResponse.yaml
  src/schemas/EnvironmentLogPaginatedResponseList.yaml
  src/schemas/EnvironmentResponse.yaml
  src/schemas/EnvironmentStatsResponse.yaml
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/EventPaginatedResponseList.yaml
  src/schemas/EventResponse.yaml
  src/schemas/InviteMemberResponse.yaml
  src/schemas/InvoiceResponse.yaml
  src/schemas/LogPaginatedResponseList.yaml
  src/schemas/LogicalDatabaseResponse.yaml
  src/schemas/MemberResponse.yaml
  src/schemas/OrganizationResponse.yaml
  src/schemas/ProjectCurrentCostResponse.yaml
  src/schemas/ProjectDeploymentRuleResponse.yaml
  src/schemas/ProjectResponse.yaml
  src/schemas/RemainingCredits.yaml
  src/schemas/SecretResponse.yaml
  src/schemas/ServiceResponse.yaml
  src/schemas/_index.yaml
  src/schemas/enums/BuildPackLanguage.yaml
Labels: enhancement

#170 Add deploy all applications endpoint
  src/openapi.yaml
  src/resources/EnvironmentApplicationDeploy.yaml
  src/schemas/DeployAllRequest.yaml
Labels: new-feature

#166 Add api token API
  src/openapi.yaml
  src/parameters/path/apiTokenId.yaml
  src/resources/OrganizationApiToken.yaml
  src/resources/OrganizationApiTokenRef.yaml
  src/schemas/OrganizationApiTokenCreateRequest.yaml
  src/schemas/OrganizationApiTokenCreateResponse.yaml
  src/schemas/OrganizationApiTokenResponse.yaml
  src/schemas/OrganizationApiTokenResponseList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/OrganizationApiTokenScope.yaml
Labels: new-feature

#173 Fix project deployment rules order api
  src/schemas/ProjectDeploymentRulesPriorityOrderRequest.yaml
Labels: bug
