Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-12, with the labels that each got.

#319 feat: Make a job triggered for many events
  src/schemas/enums/JobScheduleEvent.yaml
  src/schemas/job/JobRequest.yaml
  src/schemas/job/JobResponse.yaml
Labels: enhancement

#320 Fix job request
  src/schemas/job/JobRequest.yaml
Labels: bug, enhancement

#321 feat: add job for API variable scope
  src/schemas/enums/APIVariableScope.yaml
Labels: new-feature

#322 Fix service deploy endpoints
  src/openapi.yaml
  src/resources/EnvironmentServiceDeploy.yaml
  src/schemas/DeployAllRequest.yaml
Labels: bug

#323 fix: Remove application sticky session on update
  src/schemas/ApplicationEditRequest.yaml
Labels: bug

#325 feat: add for database and container a description field
  src/schemas/ContainerRequest.yaml
  src/schemas/DatabaseEditRequest.yaml
  src/schemas/DatabaseRequest.yaml
Labels: enhancement

#326 feat: Add job last commits
  src/openapi.yaml
  src/resources/JobCommit.yaml
Labels: enhancement

#327 feat: Add job default advanced settings
  src/openapi.yaml
  src/resources/DefaultJobAdvancedSettings.yaml
Labels: enhancement

#328 feat: Add deploy job with commit id
  src/schemas/job/JobDeployRequest.yaml
Labels: enhancement

#330 fixing text
  src/resources/job/JobDeploy.yaml
Labels: enhancement

#332 fix: job linked service type
  src/schemas/enums/LinkedServiceType.yaml
Labels: bug
