Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-06, with the labels that each got.

#216 feat: add horizontal pod autoscaling advanced setting
  src/schemas/ApplicationAdvancedSettings.yaml
Labels: enhancement

#215 fix: change mb to gb as the default unit for database creation
  src/schemas/DatabaseRequest.yaml
Labels: bug

#209 Add force request param when disconnect github app
  src/resources/OrganizationGithubAppDisconnect.yaml
Labels: enhancement

#217 correct units consistency and specify units
  src/schemas/Cluster.yaml
  src/schemas/ClusterBase.yaml
  src/schemas/EnvironmentDatabasesCurrentMetricResponse.yaml
  src/schemas/InstanceResponse.yaml
  src/schemas/MetricCPUDatapointResponse.yaml
  src/schemas/MetricMemoryDatapointResponse.yaml
  src/schemas/MetricStorageDatapointResponse.yaml
  src/schemas/StorageDiskResponse.yaml
Labels: enhancement

#212 add EC2 documentation
  src/schemas/ClusterBase.yaml
  src/schemas/_index.yaml
  src/schemas/enums/Kubernetes.yaml
Labels: new-feature

#220 fix: update cluster to fit current behavior
  src/schemas/ClusterBase.yaml
  src/schemas/ClusterFeatureRequest.yaml
  src/schemas/ClusterRequest.yaml
  src/schemas/ClusterResponse.yaml
  src/schemas/_index.yaml
Labels: enhancement

#222 feat: Add infra logs api
  src/openapi.yaml
  src/resources/OrganizationClusterLogs.yaml
  src/schemas/ClusterLogsResponse.yaml
  src/schemas/ClusterLogsResponseList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/ClusterStep.yaml
Labels: enhancement

#224 fix: cluster features format
  generator/post_generation_scripts/go.sh
  generator/post_generation_scripts/python.sh
  generator/post_generation_scripts/typescript-axios.sh
  src/schemas/ClusterResponse.yaml
Labels: bug

#225 added deployment history for db and fixed response for app history
  src/openapi.yaml
  src/resources/DatabaseDeploymentHistory.yaml
  src/schemas/DeploymentHistoryDatabasePaginatedResponseList.yaml
  src/schemas/DeploymentHistoryDatabaseResponse.yaml
  src/schemas/DeploymentHistoryResponse.yaml
Labels: new-feature

#228 Add last_deployment_date to status
  src/schemas/Status.yaml
Labels: enhancement

#229 fix: underlying_error should be in error block
  src/schemas/ClusterLogsResponse.yaml
Labels: bug

#230 feat: Add last execution id in cluster status response
  src/schemas/ClusterStatusResponse.yaml
Labels: enhancement

#231 feat: add description for last_execution_id
  src/schemas/ClusterStatusResponse.yaml
Labels: enhancement
