Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-08, with the labels that each got.

#243 fix: Add linked service information on secrets
  src/schemas/SecretResponse.yaml
Labels: bug

#244 fix: Remove description from enum refs
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/SecretResponse.yaml
  src/schemas/enums/EnvironmentVariableServiceType.yaml
Labels: bug

#246 fix: Use common enum for every service type
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/SecretResponse.yaml
  src/schemas/_index.yaml
  src/schemas/enums/EnvironmentVariableServiceType.yaml
  src/schemas/enums/LinkedServiceType.yaml
Labels: chore

#248 fix: update required fields for aws credentials request
  src/schemas/AwsCredentialsRequest.yaml
Labels: enhancement

#240 Improve environment cluster response
  src/schemas/EnvironmentResponse.yaml
Labels: enhancement

#245 chore: Add clients generation on pull requests
  .github/workflows/generate-clients.yaml
Labels: chore

#250 feat: add get routes for credentials
  src/resources/CloudProviderAWSCredentialsRef.yaml
  src/resources/CloudProviderDOCredentialsRef.yaml
  src/resources/CloudProviderScalewayCredentialsRef.yaml
Labels: new-feature

#252 Improve Container API
  src/openapi.yaml
  src/resources/ContainerContributor.yaml
  src/resources/ContainerDatabase.yaml
  src/resources/ContainerDatabaseRef.yaml
  src/resources/ContainerDeploymentHistory.yaml
  src/resources/ContainerDeploymentRestriction.yaml
  src/resources/ContainerDeploymentRestrictionRef.yaml
  src/resources/ContainerEnvironmentVariableAlias.yaml
  src/resources/ContainerEvent.yaml
  src/resources/ContainerLink.yaml
  src/resources/ContainerMetricCpu.yaml
  src/resources/ContainerMetricHealthCheck.yaml
  src/resources/ContainerMetricMemory.yaml
  src/resources/ContainerMetricRestart.yaml
  src/resources/ContainerMetricStorage.yaml
  src/resources/ContainerPreviewEnvironment.yaml
  src/resources/ContainerTag.yaml
  src/resources/ContainerTagHistory.yaml
  src/resources/ContainerTagRef.yaml
  src/resources/EnvironmentApplicationCurrentInstance.yaml
  src/resources/EnvironmentContainerCurrentInstance.yaml
  src/resources/OrganizationContainerAutoDeploy.yaml
  src/resources/OrganizationContainerPreview.yaml
  src/resources/OrganizationContainerRegistry.yaml
  src/resources/OrganizationContainerRegistryRef.yaml
  src/schemas/ContainerDeploymentRestrictionRequest.yaml
  src/schemas/ContainerDeploymentRestrictionResponse.yaml
  src/schemas/ContainerDeploymentRestrictionResponseList.yaml
  src/schemas/ContainerTagsResponse.yaml
  src/schemas/DeploymentHistoryContainerPaginatedResponseList.yaml
  src/schemas/DeploymentHistoryContainerResponse.yaml
  src/schemas/OrganizationContainerAutoDeployRequest.yaml
  src/schemas/OrganizationContainerPreviewRequest.yaml
  src/schemas/_index.yaml
  src/schemas/enums/EnvironmentVariableScope.yaml
Labels: enhancement

#255 Add cluster advanced settings
  src/openapi.yaml
  src/resources/OrganizationClusterAdvancedSettings.yaml
  src/schemas/ClusterAdvancedSettings.yaml
Labels: new-feature

#256 fix AvailableContainerRegistry endpoint
  src/openapi.yaml
  src/resources/AvailableContainerRegistry.yaml
Labels: bug

#257 Add info for registry url
  src/schemas/ContainerRegistryRequest.yaml
Labels: chore

#241 Change minimum storage size
  src/schemas/ServiceStorageRequest.yaml
Labels: bug

#238 Fix default application & database cpu and memory
  src/schemas/ApplicationEditRequest.yaml
  src/schemas/ApplicationRequest.yaml
  src/schemas/ApplicationResponse.yaml
  src/schemas/DatabaseEditRequest.yaml
  src/schemas/DatabaseRequest.yaml
  src/schemas/DatabaseResponse.yaml
Labels: enhancement

#259 Expose default application advanced settings
  src/openapi.yaml
  src/resources/DefaultApplicationAdvancedSettings.yaml
Labels: enhancement

#258 fix deploy all endpoint
  src/openapi.yaml
  src/resources/EnvironmentServiceDeploy.yaml
  src/schemas/DeployAllRequest.yaml
Labels: bug
