Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-10, with the labels that each got.

#288 fix: improve dockerhub doc-api
  src/schemas/ContainerRegistryRequest.yaml
  src/schemas/ContainerRequest.yaml
Labels: enhancement

#291 Fix client repositories push
  .github/workflows/generate-clients.yaml
Labels: chore

#290 fix: Add auto_preview on container request
  src/schemas/ApplicationEditRequest.yaml
  src/schemas/ApplicationRequest.yaml
  src/schemas/ApplicationResponse.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/ContainerResponse.yaml
Labels: enhancement

#289 fix: Remove useless enum
  src/schemas/_index.yaml
  src/schemas/enums/DefaultMemberRole.yaml
Labels: enhancement

#284 chore: Improve custom role descriptions
  src/schemas/OrganizationCustomRoleResponse.yaml
  src/schemas/OrganizationCustomRoleUpdateRequest.yaml
Labels: enhancement

#293 feat: Attach role_id on member invitation
  src/schemas/InviteMemberRequest.yaml
Labels: enhancement

#294 feat: Expose role_id & role_name on invitation API
  src/schemas/InviteMemberResponse.yaml
  src/schemas/MemberResponse.yaml
  src/schemas/MemberRoleUpdateRequest.yaml
Labels: enhancement

#298 Add sub object for cluster response in regsitry
  src/schemas/ContainerRegistryClusterResponse.yaml
  src/schemas/ContainerRegistryResponse.yaml
Labels: enhancement

#299 chore: add instance types by localization endpoints
  src/openapi.yaml
  src/parameters/path/region.yaml
  src/parameters/path/zone.yaml
  src/resources/CloudProviderAWSEKSInstanceType.yaml
  src/resources/CloudProviderAWSEc2InstanceType.yaml
  src/resources/CloudProviderScalewayKapsuleInstanceType.yaml
  src/schemas/ClusterInstanceTypeResponse.yaml
Labels: enhancement

#301 fix: cloud provider kind
  src/schemas/enums/CloudProvider.yaml
Labels: bug

#303 fix: add missing invite member id
  src/parameters/_index.yaml
Labels: bug

#306 removing application-db link endpoints
  src/openapi.yaml
  src/resources/ApplicationDatabase.yaml
  src/resources/ApplicationDatabaseRef.yaml
  src/resources/ApplicationLogicalDatabase.yaml
  src/resources/ApplicationLogicalDatabaseRef.yaml
  src/resources/ContainerLogicalDatabase.yaml
  src/resources/ContainerLogicalDatabaseRef.yaml
Labels: bug
