Repository Qovery/qovery-openapi-spec, pull requests merged in 2022-11, with the labels that each got.

#307 fix: log response version
  src/schemas/LogResponse.yaml
Labels: bug

#308 Add endpoint for log v2
  src/openapi.yaml
  src/resources/EnvironmentLogs.yaml
  src/schemas/EnvironmentLogsResponse.yaml
  src/schemas/EnvironmentLogsResponseList.yaml
Labels: enhancement

#309 fix: Add logs structures to index
  src/schemas/_index.yaml
Labels: bug, enhancement

#310 Add main endpoint for job
  src/openapi.yaml
  src/parameters/path/jobId.yaml
  src/resources/job/EnvironmentJob.yaml
  src/resources/job/EnvironmentJobStatus.yaml
  src/resources/job/Job.yaml
  src/resources/job/JobAdvancedSettings.yaml
  src/resources/job/JobCurrentInstance.yaml
  src/resources/job/JobDeploy.yaml
  src/resources/job/JobDeploymentHistory.yaml
  src/resources/job/JobEnvironmentVariable.yaml
  src/resources/job/JobEnvironmentVariableAlias.yaml
  src/resources/job/JobEnvironmentVariableOverride.yaml
  src/resources/job/JobEnvironmentVariableRef.yaml
  src/resources/job/JobRestart.yaml
  src/resources/job/JobSecret.yaml
  src/resources/job/JobSecretAlias.yaml
  src/resources/job/JobSecretOverride.yaml
  src/resources/job/JobSecretRef.yaml
  src/resources/job/JobStatus.yaml
  src/resources/job/JobStop.yaml
  src/resources/job/JobVariableImport.yaml
  src/schemas/_index.yaml
  src/schemas/enums/JobScheduleEvent.yaml
  src/schemas/job/DeploymentHistoryJobPaginatedResponseList.yaml
  src/schemas/job/DeploymentHistoryJobResponse.yaml
  src/schemas/job/JobAdvancedSettings.yaml
  src/schemas/job/JobDeployRequest.yaml
  src/schemas/job/JobRequest.yaml
  src/schemas/job/JobResponse.yaml
  src/schemas/job/JobResponseList.yaml
Labels: enhancement

#311 fix: add type environment logs
  src/schemas/EnvironmentLogsResponse.yaml
Labels: bug

#312 feat: Add default container advanced settings
  src/openapi.yaml
  src/resources/DefaultContainerAdvancedSettings.yaml
Labels: enhancement

#314 fix: add jobs for env deployments history
  src/schemas/DeploymentHistoryEnvironmentResponse.yaml
Labels: enhancement

#315 fix: job id path
  src/parameters/_index.yaml
Labels: bug

#313 fix: Update default values for Job
  src/schemas/job/JobAdvancedSettings.yaml
  src/schemas/job/JobRequest.yaml
Labels: enhancement

#316 fix: Add job description
  src/schemas/job/JobRequest.yaml
Labels: bug, chore

#317 Add environment statuses endpoint
  src/openapi.yaml
  src/resources/EnvironmentStatuses.yaml
  src/schemas/EnvironmentStatuses.yaml
Labels: enhancement, chore
