Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-07, with the labels that each got.

#401 feat: Set variable value optional
  src/schemas/EnvironmentVariableRequest.yaml
  src/schemas/Value.yaml
Labels: enhancement

#409 feat: Add endpoint to get audit log targets
  src/openapi.yaml
  src/resources/OrganizationEventTarget.yaml
  src/schemas/OrganizationEventTargetResponse.yaml
  src/schemas/OrganizationEventTargetResponseList.yaml
Labels: new-feature

#412 feat: add endpoint to clone application, container, job and database
  src/openapi.yaml
  src/resources/ApplicationClone.yaml
  src/resources/ContainerClone.yaml
  src/resources/DatabaseClone.yaml
  src/resources/JobClone.yaml
  src/schemas/CloneApplicationRequest.yaml
  src/schemas/CloneContainerRequest.yaml
  src/schemas/CloneDatabaseRequest.yaml
  src/schemas/CloneJobRequest.yaml
  src/schemas/_index.yaml
Labels: new-feature

#416 change the response when creating a variable alias
  src/resources/variable/VariableAlias.yaml
  src/schemas/_index.yaml
  src/schemas/variable/VariableAlias.yaml
  src/schemas/variable/VariableOverride.yaml
  src/schemas/variable/VariableResponse.yaml
Labels: chore

#418 chore(autodelete): Remove all autodelete from the API
  src/schemas/EnvironmentDeploymentRuleEditRequest.yaml
  src/schemas/EnvironmentDeploymentRuleResponse.yaml
  src/schemas/ProjectDeploymentRuleRequest.yaml
Labels: enhancement

#417 feat: Set every variable value optional
  src/schemas/EnvironmentVariableEditRequest.yaml
  src/schemas/SecretEditRequest.yaml
  src/schemas/SecretRequest.yaml
Labels: enhancement

#419 feat(COR-683): add api to create, update, delete and list variable en…
  src/openapi.yaml
  src/resources/variable/Variable.yaml
  src/resources/variable/VariableOverride.yaml
  src/resources/variable/VariableRef.yaml
  src/schemas/_index.yaml
  src/schemas/variable/VariableEditRequest.yaml
  src/schemas/variable/VariableRequest.yaml
  src/schemas/variable/VariableResponseList.yaml
Labels: new-feature

#421 fix: Align doc with current API
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
  src/schemas/job/JobAdvancedSettings.yaml
Labels: enhancement

#423 feat(port): Add support for TCP and UDP ports
  src/schemas/enums/PortProtocol.yaml
Labels: enhancement
