Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-10, with the labels that each got.

#452 feat(COR-715) add INVALID_CREDENTIALS in cluster state
  src/schemas/ClusterResponse.yaml
  src/schemas/ClusterStatusGetResponse.yaml
  src/schemas/ClusterStatusResponse.yaml
  src/schemas/_index.yaml
  src/schemas/enums/ClusterState.yaml
Labels: enhancement

#453 fix(schemas): fix registry type which can be null
  src/schemas/job/JobResponse.yaml
Labels: bug

#454 fix(schemas): turn option registry into optionnal
  src/schemas/job/JobResponse.yaml
Labels: bug

#455 feat: Add associated registry details in job & container response
  src/schemas/ContainerRegistryProviderDetailsResponse.yaml
  src/schemas/ContainerResponse.yaml
  src/schemas/_index.yaml
  src/schemas/job/JobResponse.yaml
Labels: enhancement

#450 feat(COR-719) add generate certificate flag to custom domain
  src/resources/ApplicationCustomDomainRef.yaml
  src/schemas/CustomDomainRequest.yaml
Labels: enhancement

#457 fix: add generate_certificate value when listing custom domains
  src/schemas/CustomDomainResponse.yaml
Labels: enhancement

#459 feat: Add cluster delete mode
  src/resources/OrganizationClusterRef.yaml
  src/schemas/enums/ClusterDeleteMode.yaml
Labels: enhancement

#460 fix: Add ClusterDeleteMode to enum
  src/schemas/_index.yaml
Labels: bug

#461 feat: Allow multiple services to be stopped or deleted
  src/openapi.yaml
  src/resources/EnvironmentServiceDelete.yaml
  src/resources/EnvironmentServiceStop.yaml
  src/schemas/EnvironmentServiceIdsAllRequest.yaml
  src/schemas/_index.yaml
Labels: enhancement

#462 fix: make generate_certificate required
  src/schemas/CustomDomainRequest.yaml
Labels: chore

#463 chore: upgrade typescript axios
  .github/workflows/generate-clients.yaml
  generator/configs/typescript-axios-ws.yaml
Labels: enhancement

#464 fix: available role response required properties
  src/schemas/OrganizationAvailableRoleResponse.yaml
Labels: enhancement

#410 chore: remove unused endpoints
  src/openapi.yaml
  src/resources/ApplicationEvent.yaml
  src/resources/ApplicationEventLastId.yaml
  src/resources/ApplicationEventTail.yaml
  src/resources/DatabaseEvent.yaml
  src/resources/DatabaseEventLastId.yaml
  src/resources/DatabaseEventTail.yaml
Labels: enhancement

#466 doc: Update cluster delete mode description
  src/schemas/enums/ClusterDeleteMode.yaml
Labels: enhancement

#467 fix: config typescript axios stringEnum
  generator/configs/typescript-axios-ws.yaml
Labels: chore

#465 chore: Add npm test step CI
  .github/workflows/openapi-test.yaml
  src/schemas/ClusterRequest.yaml
  src/schemas/ClusterResponse.yaml
  src/schemas/CommitResponse.yaml
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/Healthcheck.yaml
  src/schemas/InviteMemberRequest.yaml
  src/schemas/InviteMemberResponse.yaml
  src/schemas/MemberResponse.yaml
  src/schemas/OrganizationEventResponse.yaml
  src/schemas/Probe.yaml
  src/schemas/SecretResponse.yaml
  src/schemas/enums/Kubernetes.yaml
  src/schemas/enums/LinkedServiceType.yaml
  src/schemas/enums/OrganizationEventSubTargetType.yaml
  src/schemas/job/DeploymentHistoryJobResponse.yaml
  src/schemas/variable/VariableResponse.yaml
Labels: chore

#469 fix(schemas): add missing required fields
  src/schemas/job/JobResponse.yaml
Labels: bug

#468 feat: add image mirroring mode into the advanced settings of a cluster
  src/schemas/ClusterAdvancedSettings.yaml
  src/schemas/_index.yaml
  src/schemas/enums/RegistryMirroringMode.yaml
Labels: enhancement

#471 fix: Set mandatory source for JobResponse
  .github/workflows/generate-clients.yaml
  src/schemas/ContainerResponse.yaml
  src/schemas/ContainerSource.yaml
  src/schemas/_index.yaml
  src/schemas/job/JobResponse.yaml
Labels: enhancement

#472 fix: remove the results fields inside the stages object in GetEnviron…
  src/schemas/DeploymentStageWithServiceStatusesList.yaml
  src/schemas/EnvironmentStatusesWithStages.yaml
  src/schemas/_index.yaml
Labels: chore

#474 fix(responses): add missing required fields
  src/schemas/ApplicationResponse.yaml
  src/schemas/EnvironmentResponse.yaml
Labels: bug

#475 feat: Add git token api
  src/openapi.yaml
  src/resources/GitToken.yaml
  src/resources/OrganizationAccountGitRepositoryBitbucket.yaml
  src/resources/OrganizationAccountGitRepositoryBitbucketBranch.yaml
  src/resources/OrganizationAccountGitRepositoryGithub.yaml
  src/resources/OrganizationAccountGitRepositoryGithubBranch.yaml
  src/resources/OrganizationAccountGitRepositoryGitlab.yaml
  src/resources/OrganizationAccountGitRepositoryGitlabBranch.yaml
  src/schemas/ApplicationGitRepositoryRequest.yaml
  src/schemas/GitTokenResponse.yaml
  src/schemas/GitTokenResponseList.yaml
  src/schemas/_index.yaml
Labels: enhancement

#476 fix: Fix structure git token list
  src/schemas/_index.yaml
Labels: enhancement

#477 Add first Helm API
  src/openapi.yaml
  src/parameters/_index.yaml
  src/parameters/path/helmId.yaml
  src/resources/DefaultHelmAdvancedSettings.yaml
  src/resources/helm/EnvironmentHelm.yaml
  src/resources/helm/EnvironmentHelmStatus.yaml
  src/resources/helm/Helm.yaml
  src/resources/helm/HelmAdvancedSettings.yaml
  src/resources/helm/HelmDeploy.yaml
  src/resources/helm/HelmDeploymentHistory.yaml
  src/resources/helm/HelmDeploymentRestriction.yaml
  src/resources/helm/HelmDeploymentRestrictionRef.yaml
  src/resources/helm/HelmRedeploy.yaml
  src/resources/helm/HelmRestart.yaml
  src/resources/helm/HelmStatus.yaml
  src/resources/helm/HelmStop.yaml
  src/resources/helm/HelmVariableImport.yaml
  src/schemas/_index.yaml
  src/schemas/enums/HelmForceEvent.yaml
  src/schemas/helm/DeploymentHistoryHelmPaginatedResponseList.yaml
  src/schemas/helm/DeploymentHistoryHelmResponse.yaml
  src/schemas/helm/HelmAdvancedSettings.yaml
  src/schemas/helm/HelmDeployRequest.yaml
  src/schemas/helm/HelmDeploymentRestrictionRequest.yaml
  src/schemas/helm/HelmDeploymentRestrictionResponse.yaml
  src/schemas/helm/HelmDeploymentRestrictionResponseList.yaml
  src/schemas/helm/HelmRequest.yaml
  src/schemas/helm/HelmResponse.yaml
  src/schemas/helm/HelmResponseList.yaml
Labels: enhancement

#478 feat: Add git token id in service git repo response
  src/schemas/ApplicationGitRepositoryResponse.yaml
Labels: enhancement

#479 feat(helm): Add deployment history
  src/openapi.yaml
  src/schemas/helm/DeploymentHistoryHelmResponse.yaml
Labels: enhancement

#481 fix(helm): Display helm section under environment
  src/openapi.yaml
Labels: bug

#482 fix(git-tokens): preserve previous params order
  src/resources/OrganizationAccountGitRepositoryBitbucketBranch.yaml
  src/resources/OrganizationAccountGitRepositoryGithubBranch.yaml
  src/resources/OrganizationAccountGitRepositoryGitlabBranch.yaml
Labels: bug

#483 feat: add nginx advanced settings
  src/schemas/ClusterAdvancedSettings.yaml
Labels: enhancement

#484 fix: NGINX advanced settings naming
  src/schemas/ClusterAdvancedSettings.yaml
Labels: enhancement

#480 feat: Add git token crud api
  src/openapi.yaml
  src/parameters/_index.yaml
  src/parameters/path/gitTokenId.yaml
  src/resources/GitToken.yaml
  src/resources/GitTokenRef.yaml
  src/schemas/GitTokenRequest.yaml
  src/schemas/GitTokenResponse.yaml
  src/schemas/_index.yaml
Labels: enhancement

#485 feat: Add git token name in service response
  src/schemas/ApplicationGitRepositoryResponse.yaml
Labels: enhancement

#486 chore: Temporary endpoints to migrate git
  src/openapi.yaml
  src/resources/OrganizationAccountGitAuthProviderTemp.yaml
  src/resources/OrganizationAccountGitRepositoryBitbucketTemp.yaml
  src/resources/OrganizationAccountGitRepositoryGithubTemp.yaml
  src/resources/OrganizationAccountGitRepositoryGitlabTemp.yaml
Labels: chore

#487 feat: Get single token & associated services
  src/openapi.yaml
  src/resources/GitTokenAssociatedServices.yaml
  src/resources/GitTokenRef.yaml
  src/schemas/GitTokenAssociatedServiceResponse.yaml
  src/schemas/GitTokenAssociatedServicesResponseList.yaml
  src/schemas/GitTokenResponse.yaml
  src/schemas/_index.yaml
  src/schemas/enums/GitTokenAssociatedServiceType.yaml
Labels: enhancement

#489 feat: add workspace for the git token list
  src/schemas/GitTokenResponse.yaml
Labels: enhancement
