Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-08, with the labels that each got.

#425 feat: add node affinity and pod anti affinity options
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
  src/schemas/job/JobAdvancedSettings.yaml
Labels: new-feature

#426 fix(environment-statuses): export interface
  src/schemas/_index.yaml
Labels: bug

#422 fix: fixed text
  src/resources/ApplicationEnvironmentVariableAlias.yaml
  src/resources/ApplicationSecretAlias.yaml
  src/resources/ContainerEnvironmentVariableAlias.yaml
  src/resources/ContainerSecretAlias.yaml
  src/resources/EnvironmentEnvironmentVariableAlias.yaml
  src/resources/EnvironmentSecretAlias.yaml
  src/resources/ProjectEnvironmentVariableAlias.yaml
  src/resources/ProjectSecretAlias.yaml
  src/resources/job/JobEnvironmentVariableAlias.yaml
  src/resources/job/JobSecretAlias.yaml
  src/resources/variable/Variable.yaml
  src/resources/variable/VariableAlias.yaml
  src/resources/variable/VariableOverride.yaml
  src/schemas/variable/VariableAlias.yaml
  src/schemas/variable/VariableAliasRequest.yaml
  src/schemas/variable/VariableEditRequest.yaml
  src/schemas/variable/VariableOverride.yaml
  src/schemas/variable/VariableOverrideRequest.yaml
  src/schemas/variable/VariableRequest.yaml
  src/schemas/variable/VariableResponse.yaml
Labels: bug

#428 feat: Add edit account for communication email
  src/resources/AccountInformation.yaml
  src/schemas/_index.yaml
  src/schemas/account/AccountInfoEditRequest.yaml
  src/schemas/account/AccountInfoResponse.yaml
Labels: enhancement

#429 fix(deployment-restrictions): fix path
  src/openapi.yaml
  src/parameters/_index.yaml
Labels: bug

#430 fix(deployment-restrictions): fix list schema
  src/schemas/ApplicationDeploymentRestrictionResponseList.yaml
Labels: bug

#432 fix: removed non existing tag endpoints
  src/openapi.yaml
  src/resources/ApplicationTag.yaml
  src/resources/ApplicationTagRef.yaml
  src/schemas/TagRequest.yaml
  src/schemas/TagResponse.yaml
  src/schemas/TagResponseList.yaml
  src/schemas/_index.yaml
Labels: bug

#431 fix: Set communication email not nullable
  src/schemas/account/AccountInfoEditRequest.yaml
Labels: enhancement

#433 chore(spec): Add documentation for links response
  src/schemas/LinkResponse.yaml
Labels: enhancement

#434 Fix/add token info
  src/openapi.yaml
Labels: enhancement
