Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-04, with the labels that each got.

#379 fix: deployment stage on _index.yaml
  src/schemas/_index.yaml
Labels: bug

#381 chore: remove logicalDatabase entrypoints
  src/openapi.yaml
  src/parameters/_index.yaml
  src/parameters/path/logicalDatabaseId.yaml
  src/parameters/path/targetLogicalDatabaseId.yaml
  src/resources/DatabaseLogicalDatabase.yaml
  src/resources/LogicalDatabase.yaml
  src/resources/LogicalDatabaseApplication.yaml
  src/resources/LogicalDatabaseContainer.yaml
  src/resources/LogicalDatabaseCredentials.yaml
  src/schemas/LogicalDatabaseRequest.yaml
  src/schemas/LogicalDatabaseResponse.yaml
  src/schemas/LogicalDatabaseResponseList.yaml
  src/schemas/_index.yaml
Labels: chore

#383 fix environment status return type
  src/resources/EnvironmentStatus.yaml
Labels: bug

#384 feat: Add audit log api
  src/openapi.yaml
  src/resources/OrganizationEvent.yaml
  src/schemas/OrganizationEventResponse.yaml
  src/schemas/OrganizationEventResponseList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/OrganizationEventOrigin.yaml
  src/schemas/enums/OrganizationEventSubTargetType.yaml
  src/schemas/enums/OrganizationEventTargetType.yaml
  src/schemas/enums/OrganizationEventType.yaml
Labels: enhancement

#386 Add owned_by field for env variable
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/SecretResponse.yaml
Labels: enhancement

#385 feat: Add page-size query param for audit logs
  src/resources/OrganizationEvent.yaml
  src/schemas/OrganizationEventResponse.yaml
Labels: enhancement

#388 Add apply_deployment_rule to clone request
  src/schemas/CloneRequest.yaml
Labels: enhancement

#387 feat: Some improvements on response & query params
  src/resources/OrganizationEvent.yaml
Labels: enhancement
