Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-09, with the labels that each got.

#436 feat: Add job deployment restriction requests
  src/openapi.yaml
  src/resources/job/JobDeploymentRestriction.yaml
  src/resources/job/JobDeploymentRestrictionRef.yaml
  src/schemas/_index.yaml
  src/schemas/job/JobDeploymentRestrictionRequest.yaml
  src/schemas/job/JobDeploymentRestrictionResponse.yaml
  src/schemas/job/JobDeploymentRestrictionResponseList.yaml
Labels: enhancement

#435 feat: Add nginx advanced settings
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
Labels: enhancement

#437 feat(advanced-settings): Add security.read_only_root_filesystem
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
  src/schemas/job/JobAdvancedSettings.yaml
Labels: enhancement

#439 feat: add deployment status in cluster response
  src/schemas/ClusterResponse.yaml
  src/schemas/_index.yaml
  src/schemas/enums/ClusterDeploymentStatus.yaml
Labels: enhancement

#438 feat: Add github & gitlab & generic container registries
  src/schemas/ContainerRegistryRequest.yaml
  src/schemas/enums/ContainerRegistryKind.yaml
Labels: enhancement

#440 feat: add metrics in Stage and Service Status
  src/schemas/ServiceStepMetric.yaml
  src/schemas/ServiceStepMetrics.yaml
  src/schemas/Stage.yaml
  src/schemas/StageStepMetric.yaml
  src/schemas/StageStepMetrics.yaml
  src/schemas/Status.yaml
  src/schemas/_index.yaml
  src/schemas/enums/ServiceStepMetricName.yaml
  src/schemas/enums/StageStepMetricName.yaml
  src/schemas/enums/StepMetricStatus.yaml
Labels: enhancement

#441 feat: Add public gitlab & github crs
  src/schemas/ContainerRegistryRequest.yaml
Labels: enhancement

#442 feat: allow to set auto deploy at service level
  src/openapi.yaml
  src/resources/OrganizationJobAutoDeploy.yaml
  src/schemas/ApplicationEditRequest.yaml
  src/schemas/ApplicationRequest.yaml
  src/schemas/ApplicationResponse.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/ContainerResponse.yaml
  src/schemas/OrganizationJobAutoDeployRequest.yaml
  src/schemas/_index.yaml
  src/schemas/job/JobRequest.yaml
  src/schemas/job/JobResponse.yaml
Labels: new-feature

#444 chore(Healthchecks): Make healthcheck object required
  src/schemas/ApplicationRequest.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/Healthcheck.yaml
  src/schemas/job/JobRequest.yaml
Labels: bug

#446 chore: rename metrics to steps in status and add total deployment duration
  src/schemas/EnvironmentStatus.yaml
  src/schemas/Stage.yaml
  src/schemas/Status.yaml
Labels: chore

#447 feat: add role for token
  src/schemas/OrganizationApiTokenCreateRequest.yaml
  src/schemas/OrganizationApiTokenCreateResponse.yaml
  src/schemas/OrganizationApiTokenResponse.yaml
  src/schemas/enums/OrganizationApiTokenScope.yaml
Labels: new-feature

#448 fix: change roleId name to role_id
  src/schemas/OrganizationApiTokenCreateRequest.yaml
  src/schemas/OrganizationApiTokenCreateResponse.yaml
  src/schemas/OrganizationApiTokenResponse.yaml
Labels: bug

#449 feat: add queueing steps in metrics
  src/schemas/enums/ServiceStepMetricName.yaml
  src/schemas/enums/StageStepMetricName.yaml
Labels: enhancement
