Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-05, with the labels that each got.

#389 fix: Fix audit log request params
  src/resources/OrganizationEvent.yaml
Labels: enhancement

#390 feat: adding deployment strategy support
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
Labels: new-feature

#392 Add on_demand_preview flag to deployment rule
  src/schemas/EnvironmentDeploymentRuleEditRequest.yaml
  src/schemas/EnvironmentDeploymentRuleResponse.yaml
Labels: enhancement

#393 feat: Add id for audit log api
  src/schemas/OrganizationEventResponse.yaml
Labels: enhancement

#394 feat: add name for project/env for audit log
  src/schemas/OrganizationEventResponse.yaml
Labels: enhancement

#395 feat: Add CONFIG sub target type
  src/schemas/enums/OrganizationEventSubTargetType.yaml
Labels: enhancement

#396 feat(healthchecks): Update healthchecks for readiness and liveness
  src/schemas/ApplicationRequest.yaml
  src/schemas/ApplicationResponse.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/ContainerResponse.yaml
  src/schemas/Healthcheck.yaml
  src/schemas/Probe.yaml
  src/schemas/_index.yaml
  src/schemas/job/JobRequest.yaml
  src/schemas/job/JobResponse.yaml
Labels: enhancement

#397 chore(healthchecks): Usem more explicit var name type instead of probe
  src/schemas/Probe.yaml
Labels: chore

#402 helathchecks: Remove none type and make probe nullable
  src/schemas/Healthcheck.yaml
  src/schemas/Probe.yaml
Labels: enhancement

#399 feat: add database instance type support
  src/openapi.yaml
  src/parameters/_index.yaml
  src/parameters/path/databaseType.yaml
  src/resources/CloudProviderAWSManagedDatabaseInstanceType.yaml
  src/resources/CloudProviderAWSManagedDatabaseType.yaml
  src/resources/CloudProviderDOManagedDatabaseInstanceType.yaml
  src/resources/CloudProviderDOManagedDatabaseType.yaml
  src/resources/CloudProviderSCWManagedDatabaseInstanceType.yaml
  src/resources/CloudProviderSCWManagedDatabaseType.yaml
  src/schemas/DatabaseRequest.yaml
  src/schemas/DatabaseResponse.yaml
  src/schemas/ManagedDatabaseInstanceTypeResponse.yaml
  src/schemas/ManagedDatabaseInstanceTypeResponseList.yaml
  src/schemas/ManagedDatabaseTypeResponse.yaml
  src/schemas/ManagedDatabaseTypeResponseList.yaml
  src/schemas/_index.yaml
Labels: new-feature
