Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-01, with the labels that each got.

#333 feat: Add get member invitation
  src/resources/OrganizationInviteMemberRef.yaml
Labels: enhancement

#334 feat: Add forceEvent request param to job deploy endpoint
  src/resources/job/JobDeploy.yaml
  src/schemas/_index.yaml
  src/schemas/enums/JobForceEvent.yaml
Labels: enhancement

#336 feat: add termination_grace_period_seconds support to advanced settings
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
  src/schemas/job/JobAdvancedSettings.yaml
Labels: new-feature

#337 fix(invite-member): adding missing property in response body
  src/schemas/InviteMemberResponse.yaml
Labels: enhancement

#338 feat: add vpc flow logs to cluster advanced settings
  .github/workflows/generate-clients.yaml
  src/schemas/ClusterAdvancedSettings.yaml
Labels: new-feature

#339 feat: adding vpc flow logs
  src/schemas/ClusterAdvancedSettings.yaml
Labels: new-feature

#340 feat: allow to create env var files
  src/schemas/EnvironmentVariableRequest.yaml
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/SecretRequest.yaml
  src/schemas/SecretResponse.yaml
  src/schemas/_index.yaml
  src/schemas/enums/APIVariableType.yaml
Labels: new-feature

#343 feat: Add default cluster advanced settings api
  src/openapi.yaml
  src/resources/DefaultClusterAdvancedSettings.yaml
Labels: enhancement

#344 fix(clusters): default advanced settings
  src/resources/DefaultClusterAdvancedSettings.yaml
Labels: bug

#348 feat: adding denylist and authbasic in advanced settings
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
Labels: new-feature
