Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-12, with the labels that each got.

#524 feat: add helm link
  src/openapi.yaml
  src/resources/helm/HelmLink.yaml
Labels: enhancement

#526 fix: add routing table required fields
  src/schemas/ClusterRoutingTableResponse.yaml
Labels: bug

#529 feat(cluster): Add endpoint to retrieve kubeconfig
  src/openapi.yaml
  src/resources/OrganizationClusterKubeconfig.yaml
Labels: enhancement

#527 feat: support helm repository from private registry
  src/schemas/enums/HelmRepositoryKind.yaml
Labels: enhancement

#530 feat(COR-786): add config into HelmRepositoryRequest:
  src/schemas/HelmRepositoryRequest.yaml
Labels: enhancement

#532 chore: add id in port request
  src/schemas/ServicePortRequest.yaml
Labels: enhancement

#534 chore: return skip_tls_verification in HelmRepositoryResponse
  src/schemas/HelmRepositoryResponse.yaml
Labels: enhancement

#535 fix: missing timeout sec helm response
  src/schemas/helm/HelmResponse.yaml
Labels: bug

#536 Add self_managed
  src/schemas/enums/Kubernetes.yaml
Labels: enhancement

#537 feat: GCP integration new endpoints
  src/openapi.yaml
  src/resources/CloudProviderGcpClusterFeature.yaml
  src/resources/CloudProviderGcpCredentials.yaml
  src/resources/CloudProviderGcpCredentialsRef.yaml
  src/resources/CloudProviderGcpGkeInstanceType.yaml
  src/resources/CloudProviderGcpManagedDatabaseType.yaml
  src/resources/CloudProviderGcpRegion.yaml
  src/schemas/GcpCredentialsRequest.yaml
  src/schemas/_index.yaml
  src/schemas/enums/CloudProvider.yaml
Labels: enhancement, new-feature

#538 fix(helm): mark "name" as required
  src/schemas/HelmRepositoryResponse.yaml
Labels: bug

#539 chore: update GCP credentials field name
  src/schemas/GcpCredentialsRequest.yaml
Labels: enhancement

#540 chore: rename GCP create credentials operation
  src/resources/CloudProviderGcpCredentials.yaml
Labels: enhancement

#541 feat: env statuses to return helm info
  src/resources/helm/HelmClone.yaml
  src/schemas/EnvironmentStatuses.yaml
Labels: enhancement

#542 chore: add required properties in the HelmResponse
  src/schemas/helm/HelmResponse.yaml
Labels: chore

#543 feat: add helm deploy request
  src/schemas/EnvironmentServiceIdsAllRequest.yaml
  src/schemas/_index.yaml
  src/schemas/helm/HelmDeployRequest.yaml
Labels: enhancement

#544 feat: add helm into the DeployAllRequest
  src/schemas/DeployAllRequest.yaml
Labels: enhancement

#546 feat: add helms in the DeploymentHistoryEnvironmentResponse
  src/schemas/DeploymentHistoryEnvironmentResponse.yaml
  src/schemas/_index.yaml
  src/schemas/helm/DeploymentHistoryHelmResponse.yaml
Labels: dependencies

#545 feat: add is_secret in variableResponse
  src/schemas/variable/VariableResponse.yaml
Labels: enhancement

#548 fix: update helm advanced settings
  src/schemas/helm/HelmAdvancedSettings.yaml
Labels: enhancement

#549 fix: Adapt helm override values to struct key value
  src/schemas/_index.yaml
  src/schemas/helm/HelmKeyValue.yaml
  src/schemas/helm/HelmRequest.yaml
  src/schemas/helm/HelmResponse.yaml
Labels: enhancement

#550 fix: Set correct helm overrides array input
  src/schemas/_index.yaml
  src/schemas/helm/HelmKeyValue.yaml
  src/schemas/helm/HelmKeyValues.yaml
  src/schemas/helm/HelmRequest.yaml
  src/schemas/helm/HelmResponse.yaml
Labels: breaking-change

#551 fix: helm git response
  src/schemas/helm/HelmResponse.yaml
Labels: bug
