Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-11, with the labels that each got.

#491 feat: Update audit logs types
  src/schemas/enums/OrganizationEventSubTargetType.yaml
  src/schemas/enums/OrganizationEventTargetType.yaml
Labels: enhancement

#494 fix(helm): Fix repository for helm response
  src/schemas/helm/HelmResponse.yaml
Labels: enhancement

#492 feat: Set advanced settings default values to the qovery doc
  src/resources/ApplicationAdvancedSettings.yaml
  src/resources/ContainerAdvancedSettings.yaml
  src/resources/DefaultApplicationAdvancedSettings.yaml
  src/resources/DefaultClusterAdvancedSettings.yaml
  src/resources/DefaultContainerAdvancedSettings.yaml
  src/resources/DefaultJobAdvancedSettings.yaml
  src/resources/OrganizationClusterAdvancedSettings.yaml
  src/resources/job/JobAdvancedSettings.yaml
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ClusterAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
  src/schemas/job/JobAdvancedSettings.yaml
Labels: enhancement

#495 feat(helm): Add available helm repository endpoint
  src/openapi.yaml
  src/resources/AvailableHelmRepository.yaml
  src/schemas/AvailableHelmRepositoryResponse.yaml
  src/schemas/AvailableHelmRepositoryResponseList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/HelmRepositoryKind.yaml
Labels: enhancement

#496 feat(helm): Add helm repository endpoints
  src/resources/OrganizationHelmRepository.yaml
  src/resources/OrganizationHelmRepositoryRef.yaml
  src/schemas/HelmRepositoryRequest.yaml
  src/schemas/HelmRepositoryResponse.yaml
  src/schemas/HelmRepositoryResponseList.yaml
  src/schemas/_index.yaml
Labels: enhancement

#497 feat(helm): add helm repository
  src/openapi.yaml
  src/parameters/path/helmRepositoryId.yaml
Labels: enhancement

#499 fix: add brand for credit card response
  src/schemas/CreditCardResponse.yaml
Labels: bug

#500 feat(helm): add api to get chart default values
  src/openapi.yaml
  src/resources/helm/HelmDefaultValues.yaml
Labels: enhancement

#501 feat(helm): Use oneOf for object
  src/schemas/helm/HelmResponse.yaml
Labels: enhancement

#488 Revert "chore: Temporary endpoints to migrate git (#486)"
  src/openapi.yaml
  src/resources/OrganizationAccountGitAuthProviderTemp.yaml
  src/resources/OrganizationAccountGitRepositoryBitbucketTemp.yaml
  src/resources/OrganizationAccountGitRepositoryGithubTemp.yaml
  src/resources/OrganizationAccountGitRepositoryGitlabTemp.yaml
Labels: chore

#502 fix: set parent_id and scope required when listing variables
  src/resources/variable/Variable.yaml
Labels: enhancement

#503 fix: add value and key in Variable response
  src/schemas/variable/VariableResponse.yaml
Labels: enhancement

#504 fix: add mount_path in VariableResponse
  src/schemas/variable/VariableResponse.yaml
Labels: enhancement

#505 feat: add import to variable
  src/openapi.yaml
  src/resources/variable/VariablesImport.yaml
  src/schemas/enums/APIVariableScope.yaml
Labels: enhancement

#508 fix: change to service_type into variables import
  src/resources/variable/VariablesImport.yaml
  src/schemas/_index.yaml
  src/schemas/enums/LinkedServiceType.yaml
  src/schemas/enums/ServiceTypeForVariable.yaml
Labels: enhancement

#506 feat: add ports to helm request and helm response
  src/schemas/_index.yaml
  src/schemas/enums/HelmPortProtocol.yaml
  src/schemas/helm/HelmPortRequest.yaml
  src/schemas/helm/HelmPortResponse.yaml
  src/schemas/helm/HelmPortResponseList.yaml
  src/schemas/helm/HelmRequest.yaml
  src/schemas/helm/HelmResponse.yaml
Labels: enhancement

#509 chore: Use oneOf for job type
  src/schemas/_index.yaml
  src/schemas/job/BaseJobResponse.yaml
  src/schemas/job/CronJobResponse.yaml
  src/schemas/job/JobResponse.yaml
  src/schemas/job/LifecycleJobResponse.yaml
Labels: enhancement

#510 feat: remove the double git sub-object in the helm request
  src/schemas/HelmGitRepositoryRequest.yaml
  src/schemas/_index.yaml
  src/schemas/helm/HelmRequest.yaml
Labels: dependencies

#512 feat: Allow environment status origin & trigger nullable
  src/schemas/EnvironmentStatus.yaml
  src/schemas/_index.yaml
  src/schemas/enums/EnvironmentStatusEventOrigin.yaml
Labels: enhancement

#513 feat(database): turn environment as required
  src/schemas/DatabaseResponse.yaml
Labels: enhancement

#514 refactor(services): factorize clone requests
  src/resources/ApplicationClone.yaml
  src/resources/ContainerClone.yaml
  src/resources/DatabaseClone.yaml
  src/resources/EnvironmentClone.yaml
  src/resources/JobClone.yaml
  src/schemas/CloneContainerRequest.yaml
  src/schemas/CloneDatabaseRequest.yaml
  src/schemas/CloneEnvironmentRequest.yaml
  src/schemas/CloneJobRequest.yaml
  src/schemas/CloneServiceRequest.yaml
  src/schemas/_index.yaml
Labels: enhancement

#515 feat: add helm clone
  src/openapi.yaml
  src/resources/helm/HelmClone.yaml
Labels: enhancement

#516 feat: add GCP_ARTIFACT_REGISTRY into ContainerRegistryKind
  src/schemas/enums/ContainerRegistryKind.yaml
Labels: enhancement

#517 fix: add helmRepositoryId in index.yaml
  src/parameters/_index.yaml
Labels: bug

#518 feat: Set default cluster disk size to 40Gb
  src/schemas/Cluster.yaml
  src/schemas/ClusterRequest.yaml
Labels: enhancement

#519 fix: add required fields in AvailableHelmRepositoryResponse and Availa…
  src/schemas/AvailableContainerRegistryResponse.yaml
  src/schemas/AvailableHelmRepositoryResponse.yaml
Labels: enhancement

#520 feat: change api to get helm default values
  src/openapi.yaml
  src/resources/helm/EnvironmentHelmDefaultValues.yaml
  src/resources/helm/HelmDefaultValues.yaml
  src/schemas/_index.yaml
  src/schemas/helm/HelmDefaultValuesRequest.yaml
Labels: enhancement

#443 cleanup on non-existing event endpoints
  src/openapi.yaml
  src/schemas/EventPaginatedResponseList.yaml
  src/schemas/EventResponse.yaml
  src/schemas/EventResponseList.yaml
  src/schemas/_index.yaml
Labels: bug

#521 fix: removed unused helm endpoints
  src/openapi.yaml
Labels: bug

#522 feat(helm): Add request param to select commit listing
  src/openapi.yaml
  src/parameters/_index.yaml
  src/parameters/query/helmOf.yaml
  src/resources/helm/HelmCommit.yaml
Labels: enhancement
