Repository Qovery/qovery-openapi-spec, pull requests merged in 2023-02, with the labels that each got.

#350 fix: Set correct error event for restart action
  src/schemas/enums/State.yaml
Labels: bug

#351 Add deployment groups
  src/openapi.yaml
  src/parameters/path/deploymentStageId.yaml
  src/parameters/path/serviceId.yaml
  src/parameters/path/stageId.yaml
  src/resources/deploymentStage/DeploymentStage.yaml
  src/resources/deploymentStage/DeploymentStageMove.yaml
  src/resources/deploymentStage/DeploymentStageService.yaml
  src/resources/deploymentStage/EnvironmentDeploymentStage.yaml
  src/schemas/deploymentStage/DeploymentStageRequest.yaml
  src/schemas/deploymentStage/DeploymentStageResponse.yaml
  src/schemas/deploymentStage/DeploymentStageResponseList.yaml
  src/schemas/deploymentStage/DeploymentStageServiceResponse.yaml
  src/schemas/deploymentStage/DeploymentStageServiceResponseList.yaml
Labels: enhancement

#352 removed old dependency endpoint
  src/openapi.yaml
  src/resources/ApplicationDependency.yaml
  src/resources/ApplicationDependencyRef.yaml
  src/resources/ContainerDependency.yaml
  src/resources/ContainerDependencyRef.yaml
  src/schemas/ApplicationDependencyRequest.yaml
  src/schemas/_index.yaml
Labels: breaking-change

#353 clean: Remove old update cluster endpoint
  src/openapi.yaml
  src/resources/OrganizationClusterUpdate.yaml
Labels: enhancement

#354 feat: expose mount path and var type
  src/schemas/EnvironmentVariableAlias.yaml
  src/schemas/EnvironmentVariableOverride.yaml
  src/schemas/SecretAlias.yaml
  src/schemas/SecretOverride.yaml
Labels: enhancement, chore

#356 feat: alias and override type rename
  src/schemas/EnvironmentVariableResponse.yaml
  src/schemas/SecretResponse.yaml
Labels: enhancement, chore

#357 fix: Add deployment rule at env level
  src/openapi.yaml
Labels: bug

#358 Deployment stage update api response
  src/resources/deploymentStage/DeploymentStageService.yaml
Labels: enhancement

#359 feat: add cluster advanced settings to deny database public access
  src/schemas/ClusterAdvancedSettings.yaml
Labels: new-feature

#360 feat: Improve deployment stage
  src/openapi.yaml
  src/resources/deploymentStage/DeploymentStage.yaml
  src/resources/deploymentStage/ServiceDeploymentStage.yaml
Labels: enhancement
