Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-09, with the labels that each got.

#702 feat(ENG-1807): allow users to upgrade cluster versions
  openapi.yaml
Labels: enhancement

#704 fix: add missing tag
  openapi.yaml
Labels: bug

#703 feat(COR-1018): add the service 'selector' field in the port object
  openapi.yaml
  openapitools.json
Labels: enhancement

#706 feat: adding alb controller advanced settings
  openapi.yaml
Labels: new-feature

#694 chore: Add consistent tag for Application custom domain
  openapi.yaml
Labels: enhancement
