Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-11, with the labels that each got.

#721 fix(list-aws-instance-type): boolean type for only_meets_resource_reqs
  openapi.yaml
Labels: bug

#722 feat: allow to filter eks instance with gpu
  openapi.yaml
Labels: enhancement

#723 fix: allow to filter eks instance with gpu
  openapi.yaml
Labels: enhancement, dependencies

#726 fix: fix envionment deployment history v2 response
  openapi.yaml
Labels: bug

#727 feat(COR-1078): add search image name param
  openapi.yaml
Labels: enhancement
