Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-12, with the labels that each got.

#730 feat(COR-1065) remove buildpack support
  openapi.yaml
Labels: enhancement

#731 feat(COR-1078): update deployment history
  openapi.yaml
Labels: enhancement

#725 feat(cor-1103) Add karpenter consolidation schedule
  openapi.yaml
Labels: enhancement

#733 feat(COR-1123): add list services endpoint
  openapi.yaml
Labels: new-feature

#734 fix(COR-1123): add list services endpoint
  openapi.yaml
Labels: enhancement

#735 feat(cor-1103) Improve karpenter consolidation days api
  openapi.yaml
Labels: enhancement

#737 feat: add execution_id to service status
  openapi.yaml
Labels: enhancement

#732 feat(cor-1061) Add karpenter node pools limits
  openapi.yaml
Labels: enhancement

#740 fix(list-services-by-environment-id): add tag
  openapi.yaml
Labels: bug

#741 fix(service-type): rename serviceType into service_type
  openapi.yaml
Labels: bug

#738 feat(COR-1127): lock/unlock cluster
  openapi.yaml
Labels: enhancement

#742 fix(COR-1127): change ttl_in_days into integer
  openapi.yaml
Labels: enhancement

#743 fix(COR-1127): change locked_at into date
  openapi.yaml
Labels: enhancement

#739 feat(cor-1103) Apply iso-8601 to karpenter parameters
  openapi.yaml
Labels: enhancement

#744 fix(cor-1061) Set karpenter limits as integer
  openapi.yaml
Labels: enhancement
