Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-06, with the labels that each got.

#627 Add endpoint to list charts of a repository
  openapi.yaml
Labels: enhancement

#628 Add endpoint to list image of a container registry
  openapi.yaml
Labels: enhancement

#629 Remove un-used objects
  openapi.yaml
Labels: chore

#632 Add field to pass dockerfile content in Job
  .github/workflows/generate-clients.yaml
  openapi.yaml
Labels: enhancement

#635 Use dedicated object for job response
  openapi.yaml
Labels: enhancement

#645 Use dedicated object for helm response
  openapi.yaml
Labels: enhancement

#634 feat(COR-921): add KarpenterParameters in Cluster Feature
  openapi.yaml
Labels: enhancement

#646 Fix api response type
  openapi.yaml
Labels: enhancement

#648 feat: Adding application lifecycle advanced settings
  openapi.yaml
Labels: new-feature

#647 feat(COR-854): Support extra labels for Jobs
  openapi.yaml
Labels: enhancement

#650 fix spotlight generation for oneOf
  openapi.yaml
Labels: bug

#651 Fix container registry response type
  openapi.yaml
Labels: bug

#652 Mark oneOf field as required
  openapi.yaml
Labels: enhancement

#654 feat(COR-842): Allow to force cancel environment deploy
  openapi.yaml
Labels: enhancement

#657 feat(COR-938): Karpenter external VPC
  openapi.yaml
Labels: enhancement

#659 Add lifecycle type in job
  openapi.yaml
Labels: enhancement
