Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-03, with the labels that each got.

#590 feat: adding k8s token automount adv settings
  src/schemas/ApplicationAdvancedSettings.yaml
  src/schemas/ContainerAdvancedSettings.yaml
  src/schemas/job/JobAdvancedSettings.yaml
Labels: new-feature

#591 feat: Improve git token associated services for job
  src/schemas/enums/GitTokenAssociatedServiceType.yaml
Labels: enhancement

#592 feat: add GCP custom VPC support
  src/schemas/ClusterFeatureGcpExistingVpc.yaml
  src/schemas/ClusterFeatureResponse.yaml
  src/schemas/ClusterRequest.yaml
  src/schemas/_index.yaml
Labels: enhancement

#593 Remove not needed sdk
  .github/workflows/generate-clients.yaml
Labels: chore

#594 feat(byok): Add ON_PREMISE cloud provider
  src/schemas/enums/CloudProvider.yaml
Labels: enhancement
