Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-01, with the labels that each got.

#553 fix: Set helm git repository response
  src/schemas/helm/HelmResponse.yaml
Labels: bug

#554 feat(byok): Add kubeconfig in cluster creation
  src/schemas/ClusterRequest.yaml
Labels: enhancement

#557 feat(job): Add timezone in job
  src/schemas/job/CronJobResponse.yaml
  src/schemas/job/JobRequest.yaml
Labels: enhancement

#558 chore(api): Remove /redeploy endpoint from api
  src/openapi.yaml
  src/resources/ApplicationRedeploy.yaml
  src/resources/ContainerRedeploy.yaml
  src/resources/DatabaseRedeploy.yaml
  src/resources/EnvironmentRedeploy.yaml
  src/resources/helm/HelmRedeploy.yaml
  src/resources/job/JobRedeploy.yaml
Labels: chore

#559 remove DO from cloud provider
  src/schemas/enums/CloudProvider.yaml
Labels: chore

#560 remove DOCR from container registries
  src/schemas/enums/ContainerRegistryKind.yaml
Labels: bug

#561 fix(helm): list create custom domains
  src/resources/helm/HelmCustomDomain.yaml
Labels: bug

#562 fix: Add missing DO objects
  src/schemas/enums/ContainerRegistryKind.yaml
Labels: bug

#563 chore(byok): Add cluster credentials in creation request
  src/schemas/ClusterRequest.yaml
Labels: enhancement

#564 feat(COR-821): Implement missing advanced settings deployment.custom_…
  src/schemas/helm/HelmAdvancedSettings.yaml
Labels: enhancement

#565 chore(helm): modify helm request to have same layer than helm response
  src/schemas/HelmValuesGitRepositoryRequest.yaml
  src/schemas/_index.yaml
  src/schemas/helm/HelmRequest.yaml
Labels: chore

#567 chore: remove un-used object
  src/schemas/Cluster.yaml
Labels: chore

#566 feat(COR-828): add total_computing_duration_sec in service step metrics
  src/schemas/ServiceStepMetrics.yaml
Labels: enhancement

#569 feat: Add organization id to environment response
  src/schemas/EnvironmentResponse.yaml
Labels: enhancement

#570 fix: add missing required
  src/schemas/ClusterResponse.yaml
  src/schemas/EnvironmentResponse.yaml
Labels: bug

#572 fix(projects): add missing required property
  src/schemas/ProjectResponse.yaml
Labels: bug
