Repository Qovery/qovery-openapi-spec, pull requests merged in 2024-04, with the labels that each got.

#596 fix: add missing waiting state
  src/schemas/enums/State.yaml
Labels: enhancement

#595 feat: add annotatations groups for services
  src/openapi.yaml
  src/parameters/path/annotationsGroupId.yaml
  src/resources/ApplicationAnnotationsGroup.yaml
  src/resources/ApplicationAnnotationsGroupRef.yaml
  src/resources/ContainerAnnotationsGroup.yaml
  src/resources/ContainerAnnotationsGroupRef.yaml
  src/resources/DatabaseAnnotationsGroup.yaml
  src/resources/DatabaseAnnotationsGroupRef.yaml
  src/resources/JobAnnotationsGroup.yaml
  src/resources/JobAnnotationsGroupRef.yaml
  src/resources/OrganizationAnnotationsGroup.yaml
  src/resources/OrganizationAnnotationsGroupAssociatedItems.yaml
  src/resources/OrganizationAnnotationsGroupRef.yaml
  src/schemas/Annotation.yaml
  src/schemas/OrganizationAnnotationsGroupAssociatedItemsResponse.yaml
  src/schemas/OrganizationAnnotationsGroupAssociatedItemsResponseList.yaml
  src/schemas/OrganizationAnnotationsGroupCreateRequest.yaml
  src/schemas/OrganizationAnnotationsGroupResponse.yaml
  src/schemas/OrganizationAnnotationsGroupResponseList.yaml
  src/schemas/_index.yaml
  src/schemas/enums/AnnotationsGroupAssociatedItemType.yaml
  src/schemas/enums/AnnotationsGroupScope.yaml
Labels: new-feature

#597 feat: add updated_at and created_at to the AnnotationsGroupResponse
  src/parameters/_index.yaml
  src/schemas/OrganizationAnnotationsGroupResponse.yaml
Labels: enhancement

#598 fix(annotations): scope enum and edit request
  src/resources/OrganizationAnnotationsGroupRef.yaml
  src/schemas/enums/AnnotationsGroupScope.yaml
Labels: bug

#600 feat: clone annotations groups when cloning service
  src/schemas/enums/AnnotationsGroupScope.yaml
Labels: enhancement

#602 fix: turn variable_type to required
  src/schemas/variable/VariableResponse.yaml
Labels: bug

#604 fix: turn cronjob into required
  src/schemas/job/CronJobResponse.yaml
Labels: bug

#603 feat: update create and update service to support annotations groups
  src/schemas/ApplicationEditRequest.yaml
  src/schemas/ApplicationRequest.yaml
  src/schemas/ApplicationResponse.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/ContainerResponse.yaml
  src/schemas/DatabaseEditRequest.yaml
  src/schemas/DatabaseRequest.yaml
  src/schemas/DatabaseResponse.yaml
  src/schemas/job/CronJobResponse.yaml
  src/schemas/job/JobRequest.yaml
  src/schemas/job/LifecycleJobResponse.yaml
Labels: enhancement

#605 fix: api for annotations
  src/schemas/OrganizationAnnotationsGroupResponseList.yaml
Labels: enhancement

#606 fix: annotations API
  src/openapi.yaml
  src/resources/ApplicationAnnotationsGroup.yaml
  src/resources/ContainerAnnotationsGroup.yaml
  src/resources/DatabaseAnnotationsGroup.yaml
  src/resources/JobAnnotationsGroup.yaml
  src/resources/OrganizationAnnotationsGroup.yaml
Labels: bug

#607 feat: chore(api): add Remove /redeploy endpoint from api and remove the /restart endpoint from api
  src/openapi.yaml
  src/resources/ApplicationRedeploy.yaml
  src/resources/ContainerRedeploy.yaml
  src/resources/DatabaseRedeploy.yaml
  src/resources/EnvironmentRedeploy.yaml
  src/resources/helm/HelmRedeploy.yaml
  src/resources/job/JobRedeploy.yaml
Labels: enhancement

#608 feat: change the api to provide annotationsGroups when creating or ed…
  src/schemas/ApplicationEditRequest.yaml
  src/schemas/ApplicationRequest.yaml
  src/schemas/ContainerRequest.yaml
  src/schemas/DatabaseEditRequest.yaml
  src/schemas/DatabaseRequest.yaml
  src/schemas/ServiceAnnotationRequest.yaml
  src/schemas/ServiceAnnotationsRequestList.yaml
  src/schemas/_index.yaml
  src/schemas/job/JobRequest.yaml
Labels: enhancement

#609 chore:remove unused annotations api
  src/openapi.yaml
  src/resources/ApplicationAnnotationsGroupRef.yaml
  src/resources/ContainerAnnotationsGroupRef.yaml
  src/resources/DatabaseAnnotationsGroupRef.yaml
  src/resources/JobAnnotationsGroupRef.yaml
Labels: enhancement

#610 fix: set useOneOfDiscriminatorLookup in config
  generator/configs/go.yaml
Labels: enhancement
