Repository Qovery/qovery-openapi-spec, pull requests merged in 2025-02, with the labels that each got.

#764 chore: remove references to commit id for containers and to image nam…
  openapi.yaml
Labels: chore

#766 feat(ENG-1883): add deployment queue by service id api
  openapi.yaml
Labels: enhancement

#767 fix(deployment-queue): typo environment and service requests
  openapi.yaml
Labels: bug

#768 feat(COR-1153): Select target stage for multi-stage docker files
  openapi.yaml
Labels: dependencies

#770 feat(COR-1153): Select target stage for multi-stage docker files when…
  openapi.yaml
Labels: enhancement

#772 feat(ENG-1883): add deployment request cancellation
  openapi.yaml
Labels: enhancement

#773 feat: Bump websocket-api
  websocket/websocket-openapi.yaml
Labels: enhancement

#774 fix: Remove discriminator for oneOf definitions
  websocket/websocket-openapi.yaml
Labels: enhancement

#775 fix: Add oneOf discriminator mapping details
  websocket/websocket-openapi.yaml
Labels: enhancement
