Repository Qovery/qovery-openapi-spec, pull requests merged in 2025-03, with the labels that each got.

#776 feat: Add cluster kube events
  openapi.yaml
Labels: enhancement

#777 Add role ARN for credentials
  openapi.yaml
Labels: enhancement

#778 Bump websocket api
  websocket/websocket-openapi.yaml
Labels: enhancement

#783 chore: update clients generator + update axios version
  .github/workflows/generate-clients.yaml
  generator/configs/typescript-axios-ws.yaml
  generator/configs/typescript-axios.yaml
Labels: dependencies

#785 feat(QOV-551): add last deployment date on cluster status response
  openapi.yaml
Labels: enhancement

#784 feat(QOV-38): add deployment requests count
  openapi.yaml
Labels: enhancement

#786 fix: list services by organization id add missing tags
  openapi.yaml
Labels: bug

#782 feat(COR-1182) allow to retrieve kube events by node_name or pod_name
  openapi.yaml
Labels: enhancement
